# render.yaml - Updated for Render's Free Tier

services:
  # 1. The public-facing Agent service
  - type: web
    name: agent
    env: docker
    plan: free # Use the free instance plan
    dockerfilePath: ./services/agent/Dockerfile
    dockerContext: ./services/agent
    healthCheckPath: /
    envVars:
      - key: PANDAS_EDA_URL
        value: http://pandas-eda:8001
      - key: SKLEARN_LAB_URL
        value: http://sklearn-lab:8002

  # 2. The internal Pandas service
  - type: web
    name: pandas-eda
    env: docker
    plan: free # Use the free instance plan
    dockerfilePath: ./services/pandas-eda/Dockerfile
    dockerContext: ./services/pandas-eda
    ipAllowList: []

  # 3. The internal Scikit-learn service
  - type: web
    name: sklearn-lab
    env: docker
    plan: free # Use the free instance plan
    dockerfilePath: ./services/sklearn-lab/Dockerfile
    dockerContext: ./services/sklearn-lab
    ipAllowList: []

  # 4. The public-facing Frontend Client
  - type: web
    name: client
    env: docker
    plan: free # Use the free instance plan
    dockerfilePath: ./client/Dockerfile
    dockerContext: ./client
    envVars:
      - key: NEXT_PUBLIC_AGENT_WS_URL
        # This is a placeholder. You will set the real value in the dashboard.
        value: "wss://placeholder.onrender.com"