# render.yaml - WARNING: This version makes all services public.

services:
  # 1. The public-facing Agent service
  - type: web
    name: agent
    env: docker
    dockerfilePath: ./services/agent/Dockerfile
    dockerContext: ./services/agent
    healthCheckPath: /
    envVars:
      # You would need to update these to use the public URLs of the services below
      - key: PANDAS_EDA_URL
        value: http://pandas-eda:8001
      - key: SKLEARN_LAB_URL
        value: http://sklearn-lab:8002

  # 2. The pandas service (now public)
  - type: web
    name: pandas-eda
    env: docker
    dockerfilePath: ./services/pandas-eda/Dockerfile
    dockerContext: ./services/pandas-eda

  # 3. The Scikit-learn service (now public)
  - type: web
    name: sklearn-lab
    env: docker
    dockerfilePath: ./services/sklearn-lab/Dockerfile
    dockerContext: ./services/sklearn-lab

  # 4. The public-facing Frontend Client
  - type: web
    name: client
    env: docker
    dockerfilePath: ./client/Dockerfile
    dockerContext: ./client
    envVars:
      - key: NEXT_PUBLIC_AGENT_WS_URL
        value: "wss://placeholder.onrender.com"