# render.yaml - Updated to use a single backend Dockerfile

services:
  # 1. The public-facing Agent service
  - type: web
    name: agent
    env: docker
    plan: free
    # All backend services now share the same build context
    dockerContext: ./services
    dockerfilePath: ./services/Dockerfile
    # This command starts the agent service
    startCommand: "uvicorn agent.main:app --host 0.0.0.0 --port 8000"
    healthCheckPath: /
    envVars:
      - key: PANDAS_EDA_URL
        value: http://pandas-eda:8001
      - key: SKLEARN_LAB_URL
        value: http://sklearn-lab:8002

  # 2. The internal Pandas service
  - type: pserv
    name: pandas-eda
    env: docker
    plan: free
    dockerContext: ./services
    dockerfilePath: ./services/Dockerfile
    # This command starts the pandas-eda service
    startCommand: "uvicorn pandas-eda.main:app --host 0.0.0.0 --port 8001"

  # 3. The internal Scikit-learn service
  - type: pserv
    name: sklearn-lab
    env: docker
    plan: free
    dockerContext: ./services
    dockerfilePath: ./services/Dockerfile
    # This command starts the sklearn-lab service
    startCommand: "uvicorn sklearn-lab.main:app --host 0.0.0.0 --port 8002"

  # 4. The public-facing Frontend Client (this service is unchanged)
  - type: web
    name: client
    env: docker
    plan: free
    dockerfilePath: ./client/Dockerfile
    dockerContext: ./client
    envVars:
      - key: NEXT_PUBLIC_AGENT_WS_URL
        value: "wss://placeholder.onrender.com"